# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMap

pod 'GoogleMaps', '6.1.0'
pod 'GooglePlaces', '7.3.0'
pod 'Alamofire'
pod 'SwiftyJSON'
    post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    end
end
